---
abstract: "Interact with eNom, Inc.'s reseller API"
author:
  - 'Richard Simões <rsimoes AT cpan DOT org>'
  - 'Simon Cozens <simon AT simon-cozens DOT org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  HTML::Parser: v3.67
  Module::Build: 0.3601
  Moose: 0
  Test::More: 0
  Test::Most: 0.25
  Test::Requires: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-eNom
no_index:
  namespace:
    - Net::eNom
    - WWW::eNom::Role::Commands
requires:
  Any::Moose: 0
  HTTP::Tiny: 0
  ParseUtil::Domain: 2.09
  URI: 0
  XML::LibXML::Simple: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/rsimoes/www-enom/issues
  homepage: http://search.cpan.org/dist/WWW-eNom
  repository: git://github.com/rsimoes/www-enom.git
version: v1.0.5
